FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY . .

RUN dotnet publish "AgendaApi/AgendaApi.csproj" -c Release -o /app

ENV ConnectionStrings__DefaultConnection="Data Source=AgendaTelefonica.db"

COPY AgendaTelefonica.db /app/Data/AgendaTelefonica.db

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

COPY --from=build /app .

ENTRYPOINT ["dotnet", "AgendaApi.dll"]
