FROM node:latest AS build
WORKDIR /app

COPY . .
RUN npm install
RUN npm run build
# levanto app en nginx -> mas optimo
FROM nginx:alpine
# reemplazo config de nginx para que funcionen las rutas
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/my-app/ /usr/share/nginx/html
EXPOSE 80
